### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError Failed resolution of: Ljava/util/concurrent/CompletableFuture;

### ISSUE THREAD

**Issue by jinchengwu-ola** [alexmercerind/flutter_media_metadata#22]
Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Ljava/util/concurrent/CompletableFuture;

java.lang.ClassLoader.loadClass (ClassLoader.java:469)
com.alexmercerind.flutter_media_metadata.a.onMethodCall (FlutterMediaMetadataPlugin.java:2)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:2)
io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java:2)
io.flutter.embedding.engine.dart.DartMessenger.a (DartMessenger.java:2)
io.flutter.embedding.engine.dart.DartMessenger.b (DartMessenger.java)
io.flutter.embedding.engine.dart.c.run (lambda)
android.os.Handler.handleCallback (Handler.java:739)

Not support CompletableFuture while android's minSdk is less than 24

It is similar to an flutter/plugin issue.

The solution can be refer to 
https://github.com/flutter/plugins/pull/2770/commits/0bd38d2a2cf367e2418334bd32d362c1880704be

**Comment by alexmercerind** [comment]
Fixed in #21 I
