### ISSUE TITLE
Syntax error!

### ISSUE THREAD

**Issue by cangletn** [alexmercerind/flutter_media_metadata#25]
Build failed on macOS. 
![image](https://user-images.githubusercontent.com/45934678/159887233-e53d9f50-7166-488e-bcfa-cee957eb7de9.png)

**Comment by alexmercerind** [comment]
Then fix it...

**Comment by DiscombobulatedDrag** [comment]
@cangletn I tried to run `example/macos` and it seems to work fine.
![2022-04-13 17 25 01](https://user-images.githubusercontent.com/67264966/163134203-cee8063d-3117-4281-ae5c-f32835509cd0.png)

 - Mac Pro (Late 2013)
 - macOS Monterey 12.3.1
 - Xcode 13.3.1

**Comment by cangletn** [comment]
Work with latest XCode version
