### ISSUE TITLE
Meta data scrambled when requesting meta data from a sequence of files asynchronously 

### ISSUE THREAD

**Issue by ton-An** [alexmercerind/flutter_media_metadata#4]
When requesting meta data for a list of files the meta data gets mixed up. 
The MetaDataRetriever quite often returns the same meta data twice or thrice or scrambles together a completly new set of meta data.

A quick but dirty fix is delaying each meta data request by a 100ms.

**Comment by alexmercerind** [comment]
Hi there @ton-An !

Are you retrieving metadata asynchronously (I mean two or more files at the same time)? 

I'm using this plugin in my app, [here](https://github.com/alexmercerind/harmonoid) & it works well. 
I'm asking for the metadata one at a time.

Although, I accept my fault, that it should be fixed.

Thanks for the report!

**Comment by ton-An** [comment]
Ahh, that solved it.

I was scanning the storage with the stream from `directory.list` and then immedeatly requesting meta data for the files. Making that operation synchronous worked

**Comment by alionour** [comment]
Any updates about this or a workaround

**Comment by alexmercerind** [comment]
This was actually a design problem, refactored code & changed API a bit. Fixed, calls are now multithread friendly.
