### ISSUE TITLE
Implement `MediaMetadataRetriever.release`

### ISSUE THREAD

**Issue by nt4f04uNd** [alexmercerind/flutter_media_metadata#8]

**Comment by alexmercerind** [comment]
Fixed. Added a `MediaMetadataRetriever.release` call at the end.
I believe its not going to make any difference anyway as Java isn't like C++ that's gonna leak memory when object is out of scope.
Changed API a bit aswell to keep this little plugin multi-thread friendly.
I'm not much aware about Java, I mostly make Windows & Linux libraries/plugins.
