### ISSUE TITLE
set source methods must not be performed on ui thread

### ISSUE THREAD

**Issue by nt4f04uNd** [alexmercerind/flutter_media_metadata#9]

**Comment by alexmercerind** [comment]
Hi there!
Thanks a lot for your comprehensive issue reports, but I'm not really experienced in Java or Kotlin, this plugin is really bare bones.
Most of my other plugins are for Windows or Linux (C++), I'm not specialized in asynchronous programming in Java as of now, looking forward to learn more.

**Comment by alexmercerind** [comment]
Fixed
